-- T_RFA_Domaines --
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Banques');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Zones Géographiques');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Activités');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Transactions');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('ERT');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Opérations');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Devises');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Codes Produits');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Contexte lecture carte');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Réseaux');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Litiges');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Temps');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Catalogue Produits');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Contrats');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Equipement');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('LitigesBOE');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('OpérationsBOE');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Oppositions');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Transactions frauduleuses');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Commun');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Accepteurs');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Site d''acceptation');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('ELC d''acceptation');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Prestation option d''acceptation');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Remise acquittement');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Opération rejetees');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Compensation - Opérations TI');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Imputations accepteur');
INSERT INTO dbo.T_RFA_Domaines (LB_Nom) VALUES ('Litiges - Opérations incoming');

-- T_RFA_Referentiels --
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (1, 'T_RFA_ListesBanques', 'Listes de banques', 'LBQ', 'Complexe 2');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (1, 'T_RFA_EntitesBancaires', 'Entités bancaires', 'EBQ', 'Complexe 2');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (2, 'T_RFA_ListesPays', 'Listes de pays', 'LPA', 'Complexe 2');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (2, 'T_RFA_Pays', 'Pays', 'PAY', 'Complexe 2');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (2, 'T_RFA_Regions', 'Régions France', 'REG', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (2, 'T_RFA_Departements', 'Départements France', 'DEP', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (2, 'T_RFA_Communes', 'Communes France', 'COM', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (3, 'T_RFA_NAF2008', 'NAF 2008', 'NAF', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (3, 'T_RFA_MCC', 'MCC', 'MCC', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (3, 'T_RFA_CategoriesSectorielles', 'Catégories sectorielles', 'CAS', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (3, 'T_RFA_TCC', 'TCC', 'TCC', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (4, 'T_RFA_GroupesTypesTransactions', 'Groupes de types de transactions', 'GTT', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (4, 'T_RFA_TypesTransactions', 'Types de transactions', 'TYT', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (5, 'T_RFA_GroupesERT', 'Groupes d''ERT', 'GER', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (5, 'T_RFA_ERT', 'ERT', 'ERT', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (6, 'T_RFA_GroupesTypesOperations', 'Groupes de types d''opérations', 'GTO', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (6, 'T_RFA_TypesOperations', 'Types d''opérations', 'TOP', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (7, 'T_RFA_Devises', 'Devises', 'DEV', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (8, 'T_RFA_TypesCartesMCI', 'Types de cartes Mastercard', 'TMC', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (8, 'T_RFA_TypesCartesVISA', 'Types de cartes VISA', 'TVI', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (8, 'T_RFA_TypesCartesCB', 'Types de cartes CB', 'TCB', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_CapLecTP1VISA', 'Capacité lecture terminal paiement Visa', 'C1V', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_CapLecTP1MCI', 'Capacité lecture terminal paiement Mci', 'C1M', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_CapAuthTP2MCI', 'Capacité authentification terminal paiement', 'C2M', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_CapCapTP3MCI', 'Capacité capture terminal paiement', 'C3M', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_CondFctTP4MCI', 'Conditions fonctionnement terminal paiement', 'C4M', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_IndPresPort5MCI', 'Indicateur présence porteur', 'C5M', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_IndpresEqEm6VISA', 'Indicateur présence équipement émission Visa', 'C6V', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_IndpresEqEm6', 'Indicateur présence équipement émission Mci', 'C6M', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_ModLecEqEm7CB', 'Mode lecture équipement émission CB', 'C7C', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_ModLecEqEm7VISA', 'Mode lecture équipement émission Visa', 'C7V', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_ModLecEqEm7MCI', 'Mode lecture équipement émission Mci', 'C7M', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_MethAuthPort8VISA', 'Méthode authentification porteur Visa', 'C8V', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_MethAuthPort8CB', 'Méthode authentification porteur CB', 'C8C', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_MethAuthPort8MCI', 'Méthode authentification porteur Mci', 'C8M', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_InitAuthEqEm9MCI', 'Initiateur authentification équipement émission', 'C9M', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_CapLecEq10MCI', 'Capacité lecture équipement', 'CAM', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_CapSortTP11MCI', 'Capacité sortie terminal paiement', 'CBM', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_CapSaisCodTP12MCI', 'Capacité saisie code confidentiel terminal paiement', 'CCM', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_IndTypPm13VISA', 'Indicateur type paiement', 'CDV', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (10, 'T_RFA_SystemesCompensation', 'Systèmes de compensation', 'SCO', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (10, 'T_RFA_ReseauxCartes', 'Réseaux cartes', 'RCA', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (10, 'T_RFA_CircuitsTransactions', 'Circuits de transactions', 'CIT', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (11, 'T_RFA_MotifsOperationsImpayees', 'Motifs d''opérations impayées', 'MOI', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (11, 'T_RFA_MotifsRepresentationOperations', 'Motifs de représentation impayées ', 'MOR', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (11, 'T_RFA_MotifsRejetOperations', 'Motifs de rejet d''opération', 'MRO', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (12, 'T_RFA_DateJour','Date du jour', 'DJO', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (12, 'T_RFA_DateHebdomadaire', 'Date hebdomadaire', 'DHB', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (13, 'T_RFA_VisuelsEmetteurCartes', 'Produits émetteur cartes', 'VEC', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (13, 'T_RFA_ProduitsEmetteurCartes', 'Visuels émetteur cartes', 'PEC', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (13, 'T_RFA_BinEmetteurCartes', 'BEC', 'BIN émetteur cartes', 'Complexe 1');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (14, 'T_RFA_MesureSauvegarde', 'Mesure sauvegarde', 'MSA', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (14, 'T_RFA_RetourMesureSauvegarde', 'Retour mesure sauvegarde', 'RMS', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (14, 'T_RFA_StatutElementContrat', 'Statut élément contrat', 'SEC', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (14, 'T_RFA_ModeImputationCompte', 'Mode imputation compte', 'MIC', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (14, 'T_RFA_MotifClotureCompte', 'Motif cloture compte', 'MCL', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (14, 'T_RFA_PeriodicitePrelevementCotisation', 'Périodicité prélèvement cotisation', 'PPC', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (15, 'T_RFA_StatutEquipement', 'Statut équipement', 'STE', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (15, 'T_RFA_TypeActeGestionEquipement', 'Type acte gestion équipement', 'TAG', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (15, 'T_RFA_TypeDistributionEquipement', 'Type distribution équipement', 'TDE', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (15, 'T_RFA_MotifRemplacementEquipement', 'Motif remplacement équipement', 'MRE', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (16, 'T_RFA_ActionDossierLitige', 'Action dossier litige', 'ADL', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (16, 'T_RFA_TypeDossierLitige', 'Type dossier litige', 'TDL', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (16, 'T_RFA_StatutDossierLitige', 'Statut dossier litige', 'SDL', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (16, 'T_RFA_NatureDossierLitige', 'Nature dossier litige','NDL', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (18, 'T_RFA_ReseauDeclarationOpposition', 'Réseau déclaration opposition', 'RDO', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (18, 'T_RFA_MotifOpposition', 'Motif opposition', 'MOO', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (18, 'T_RFA_StatutTraitementOperationEmission', 'Statut traitement opération émission', 'TOE', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (18, 'T_RFA_TypeMouvementOpposition', 'Type mouvement opposition', 'TMO', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (18, 'T_RFA_TypeMouvementOperation', 'Type mouvement opération', 'MOP', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (19, 'T_RFA_FormatTF', 'Format TF','FTF', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (19, 'T_RFA_NatureDeclarationTF', 'Nature déclaration TF', 'NDT', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (19, 'T_RFA_TimingOpposition', 'Timing opposition', 'TIO', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (19, 'T_RFA_TypeContrefacon', 'Type contrefacon', 'TCO', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (19, 'T_RFA_TypeFraude', 'Type fraude', 'TFR', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (20, 'T_RFA_Statut', 'Statut', 'STA', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (20, 'T_RFA_IndicateurActivation', 'Indicateur activation', 'INA', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (20, 'T_RFA_IndicateurAnnulation', 'Indicateur annulation', 'IAN', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (20, 'T_RFA_MotifStatut', 'Motif statut', 'MOS', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (20, 'T_RFA_Motif', 'Motif', 'MOT', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (20, 'T_RFA_Origine', 'Origine', 'ORI', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (20, 'T_RFA_Destinataire', 'Destinataire', 'DES', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (21, 'T_RFA_StatutSIRET', 'SSI', 'Statut SIRET', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (22, 'T_RFA_TypeSiteAcceptation', 'Type site acceptation', 'TSA', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (23, 'T_RFA_FonctionMonetique', 'Fonction monétique', 'FMO', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (23, 'T_RFA_ContexteReglementaire', 'Contexte règlementaire', 'CRE', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (23, 'T_RFA_ContextTechnique', 'Contexte technique', 'CTE', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (23, 'T_RFA_FonctionAcceptation', 'Fonction acceptation', 'FAC', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (23, 'T_RFA_ModeSelectionContexteAcceptation', 'Mode sélection contexte acceptation', 'SCA', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (23, 'T_RFA_DeclenchementAutorisation', 'Déclenchement autorisation', 'DAU', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (23, 'T_RFA_FinalisationAutorisation', 'Finalisation autorisation', 'FIA', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (23, 'T_RFA_ChoixDeviseReglementPorteur', 'Choix devise règlement porteur', 'DRP', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (23, 'T_RFA_ModeReglementPorteur', 'Mode reglement porteur', 'MRP', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (24, 'T_RFA_IndicateurPrestationOptionAcceptation', 'Indicateur prestation option acceptation', 'IPO', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (25, 'T_RFA_TypeRemettant', 'Type remettant', 'TRE', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (25, 'T_RFA_CanalAcquisitionRemise', 'Canal acquisition remise', 'CAR', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (25, 'T_RFA_NatureRemiseAcquittement', 'Nature remise acquittement', 'NRA', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (26, 'T_RFA_MotifRejetTransaction', 'Motif rejet transaction', 'MRT', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (27, 'T_RFA_NaturePorteurCarte', 'Nature porteur carte', 'NPC', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (27, 'T_RFA_IndicateurDemandeAutorisation', 'Indicateur demande autorisation', 'IDA', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (28, 'T_RFA_TypeElementImputable', 'Type élément imputable', 'TEI', 'Simple');
INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (28, 'T_RFA_RegroupementElementImputable', 'Regroupement élément imputable', 'REI', 'Simple');

INSERT INTO dbo.T_RFA_Referentiels (ID_DOM, LB_Nom, LB_NomFonctionnel, LB_Trigramme, LB_Type) VALUES (9, 'T_RFA_CompositionListesPays', 'CompositionListesPays', 'CLP', 'Complexe 2');
