-- Groupes Types Transactions --
INSERT INTO T_RFA_GroupesTypesTransactions ( LB_Code, LB_Libelle, LB_AgentCreation, LB_AgentDerniereMaj, DT_Creation, DT_DerniereMaj) VALUES ( '1', 'Paiement', 'Sopra Group', 'Sopra Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO T_RFA_GroupesTypesTransactions ( LB_Code, LB_Libelle, LB_AgentCreation, LB_AgentDerniereMaj, DT_Creation, DT_DerniereMaj) VALUES ( '2', 'Cash Advance', 'Sopra Group', 'Sopra Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO T_RFA_GroupesTypesTransactions ( LB_Code, LB_Libelle, LB_AgentCreation, LB_AgentDerniereMaj, DT_Creation, DT_DerniereMaj) VALUES ( '3', 'Retrait', 'Sopra Group', 'Sopra Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO T_RFA_GroupesTypesTransactions ( LB_Code, LB_Libelle, LB_AgentCreation, LB_AgentDerniereMaj, DT_Creation, DT_DerniereMaj) VALUES ( '4', 'Avoir', 'Sopra Group', 'Sopra Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Types Transactions --
INSERT INTO T_RFA_TypesTransactions ( LB_CodeBoa, LB_LibelleBoa, LB_LibelleBoe, LB_CodeCommun, LB_LibelleCommun, ID_GTT, LB_AgentCreation, LB_AgentDerniereMaj, DT_Creation, DT_DerniereMaj) VALUES ( '1', 'Achat', 'Sales', '1', 'Paiement', 1, 'Sopra Group', 'Sopra Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO T_RFA_TypesTransactions ( LB_CodeBoa, LB_LibelleBoa, LB_LibelleBoe, LB_CodeCommun, LB_LibelleCommun, ID_GTT, LB_AgentCreation, LB_AgentDerniereMaj, DT_Creation, DT_DerniereMaj) VALUES ( '3', 'Cash Advance', '', '2', 'Cash Advance', 2, 'Sopra Group', 'Sopra Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO T_RFA_TypesTransactions ( LB_CodeBoa, LB_LibelleBoa, LB_LibelleBoe, LB_CodeCommun, LB_LibelleCommun, ID_GTT, LB_AgentCreation, LB_AgentDerniereMaj, DT_Creation, DT_DerniereMaj) VALUES ( '4', 'Retrait', 'ATM', '3', 'Retrait DAB/GAB', 3, 'Sopra Group', 'Sopra Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO T_RFA_TypesTransactions ( LB_CodeBoa, LB_LibelleBoa, LB_LibelleBoe, LB_CodeCommun, LB_LibelleCommun, ID_GTT, LB_AgentCreation, LB_AgentDerniereMaj, DT_Creation, DT_DerniereMaj) VALUES ( '', '', 'Cash', '4', 'Retrait guichet', 3, 'Sopra Group', 'Sopra Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO T_RFA_TypesTransactions ( LB_CodeBoa, LB_LibelleBoa, LB_LibelleBoe, LB_CodeCommun, LB_LibelleCommun, ID_GTT, LB_AgentCreation, LB_AgentDerniereMaj, DT_Creation, DT_DerniereMaj) VALUES ( '5', 'Quasi Cash', '', '5', 'Quasi-cash', 1, 'Sopra Group', 'Sopra Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO T_RFA_TypesTransactions ( LB_CodeBoa, LB_LibelleBoa, LB_LibelleBoe, LB_CodeCommun, LB_LibelleCommun, ID_GTT, LB_AgentCreation, LB_AgentDerniereMaj, DT_Creation, DT_DerniereMaj) VALUES ( '9', 'Avoir', 'CREDIT', '6', 'Avoir', 4, 'Sopra Group', 'Sopra Group', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
